import time
import random

stands_jojo = ["20th Century Boy", "Achtung Baby", "Aerosmith", "Anubis", "Aqua Necklace", "Atom Heart Father", "Atum", "Baby Face", "Bad Company", "Ball Breaker", "Bags' Groove", "Bastet", "Beach Boy", "Bites the Dust", "Black Sabbath", "Blue Hawaii", "Bohemian Rhapsody", "Boku no Rhythm wo Kiitekure", "Born This Way", "Brain Storm", "Burning Down the House", "C-Moon", "California King Bed", "Cat Size", "Catch the Rainbow", "Cheap Trick", "Chocolate Disco", "Cinderella", "Civil War", "Clash", "Crazy Diamond", "Cream", "Cream Starter", "D4C Love Train", "Dark Blue Moon", "Death Thirteen", "Dirty Deeds Done Dirt Cheap", "Diver Down", "Doobie Wah!", "Doggy Style", "Dragon's Dream", "Earth Wind and Fire", "Ebony Devil", "Echoes Act 1", "Echoes Act 2", "Echoes Act 3", "Emperor", "Empress", "Enigma", "Epitaph", "Foo Fighters", "Geb", "Gold Experience", "Gold Experience Requiem", "Goo Goo Dolls", "Green Day", "Green Green Grass of Home", "Hanged Man", "Harvest", "Heaven's Door", "Hey Ya!", "Hermit Purple", "Hierophant Green", "High Priestess", "Highway Star", "Highway to Hell", "I Am a Rock", "In a Silent Way", "Jail House Lock", "Judgement", "Jumpin' Jack Flash", "Justice", "Khnum", "Killer Queen", "Killer Queen (Alternate)", "King Crimson", "King Nothing", "Kiss", "Kraft Work", "Limp Bizkit", "Little Feet", "Love Deluxe", "Love Love Deluxe (Part 8)", "Lovers", "Made in Heaven", "Magician's Red", "Man in the Mirror", "Manhattan Transfer", "Mandom", "Marilyn Manson", "Matte Kudasai", "Metallica", "Milagro Man", "Moody Blues", "Mr. President", "Notorious B.I.G", "November Rain", "Nut King Call", "Osiris", "Oasis", "Ozon Baby", "Paisley Park", "Paper Moon King", "Pearl Jam", "Planet Waves", "Purple Haze", "Ratt", "Red Hot Chili Pepper", "Rolling Stones", "Scary Monsters", "Schott Key No.1", "Schott Key No.2", "Sex Pistols", "Sheer Heart Attack", "Silver Chariot", "Silver Chariot Requiem", "Sky High", "Soft & Wet", "Soft & Wet: Go Beyond", "Soft Machine", "Space Trucking", "Speed King", "Spice Girl", "Star Platinum", "Star Platinum (Part 6)", "Sticky Fingers", "Stone Free", "Stray Cat", "Strength", "Sugar Mountain", "Sun", "Super Fly", "Surface", "Survivor", "Talking Head", "Tattoo You!", "The Fool", "The Grateful Dead", "The Hand", "The Hustle", "The Lock", "The World", "The World (Diego)", "Thoth", "Tomb of the Boom", "Tower of Gray", "Tusk Act 1", "Tusk Act 2", "Tusk Act 3", "Tusk Act 4", "Tubular Bells", "Under World", "Vitamin C", "Walking Heart", "Weather Report", "Wheel of Fortune", "White Album", "Whitesnake", "Wired", "Wonder of U", "Yo-Yo Ma", "Yellow Temperance"]
descriptions = {
    "20th Century Boy": "Grants absolute defense by making the user immovable and invulnerable while crouching.",
    "Achtung Baby": "Turns the user invisible when they cry.",
    "Aerosmith": "A miniature fighter plane that fires bullets and missiles and detects CO₂.",
    "Anubis": "A sentient sword that possesses wielders and grows stronger with each fight.",
    "Aqua Necklace": "A water-based Stand that travels through liquids and can possess people.",
    "Atom Heart Father": "Traps people inside photographs and controls the photo space.",
    "Atum": "Reads souls through poker and steals them upon defeat.",
    "Baby Face": "Creates an evolving homunculus that fights automatically.",
    "Bad Company": "A miniature army equipped with tanks, helicopters, and infantry.",
    "Ball Breaker": "Uses Infinite Spin energy to age targets and bypass dimensions.",
    "Bags' Groove": "Stores and releases objects using spatial manipulation.",
    "Bastet": "Magnetizes targets, causing metal objects to stick to them.",
    "Beach Boy": "A fishing-rod Stand that phases through matter to hook internal organs.",
    "Bites the Dust": "A time-loop bomb that kills anyone investigating the user’s identity.",
    "Black Sabbath": "A shadow Stand that impales targets with Stand arrows.",
    "Blue Hawaii": "Controls people who step on contaminated ground.",
    "Bohemian Rhapsody": "Brings fictional characters to life.",
    "Boku no Rhythm wo Kiitekure": "Invisible timed bombs triggered by proximity.",
    "Born This Way": "Attacks with freezing force when targets open something.",
    "Brain Storm": "Infects targets with aggressive flesh-eating virus colonies.",
    "Burning Down the House": "Creates ghost rooms from destroyed spaces.",
    "C-Moon": "Manipulates gravity and turns victims inside out.",
    "California King Bed": "Steals memories when targets lose bets.",
    "Cat Size": "Manipulates small cat-like creatures with hidden abilities.",
    "Catch the Rainbow": "Controls rainwater and solidifies it into weapons.",
    "Cheap Trick": "Attaches to a victim’s back and kills anyone who looks at it.",
    "Chocolate Disco": "Grid-based targeting system that auto-aims projectiles.",
    "Cinderella": "Alters people’s appearance like magical cosmetic surgery.",
    "Civil War": "Forces victims to relive guilt through materialized memories.",
    "Clash": "A shark Stand that travels through liquids and attacks from within.",
    "Crazy Diamond": "Restores objects and people to a previous state (cannot heal the user).",
    "Cream": "Erases space by consuming matter while inside a void sphere.",
    "Cream Starter": "Spray that heals wounds using flesh from others.",
    "D4C Love Train": "Redirects all misfortune away from the user across dimensions.",
    "Dark Blue Moon": "Underwater combat Stand with razor-sharp scales and barnacles.",
    "Death Thirteen": "Attacks victims within their dreams.",
    "Dirty Deeds Done Dirt Cheap": "Travels between parallel dimensions and swaps versions of people.",
    "Diver Down": "Phases into objects or bodies and restructures them internally.",
    "Doobie Wah!": "A wind-based automatic Stand that attacks breathing targets.",
    "Doggy Style": "Unravels the user’s body into flexible cords.",
    "Dragon's Dream": "A feng shui Stand that reveals lucky and unlucky positions.",
    "Earth Wind and Fire": "Shape-shifts the user into objects.",
    "Ebony Devil": "Possesses objects and grows stronger through hatred.",
    "Echoes Act 1": "Produces sound effects as physical text.",
    "Echoes Act 2": "Turns sound effects into real phenomena.",
    "Echoes Act 3": "Increases gravity on targets with '3 Freeze'.",
    "Emperor": "A controllable phantom gun with guided bullets.",
    "Empress": "A parasitic flesh Stand that grows on victims.",
    "Enigma": "Traps people inside paper when their fear 'tell' is revealed.",
    "Epitaph": "Predicts the immediate future.",
    "Foo Fighters": "A sentient colony of plankton that controls a human body.",
    "Geb": "Controls high-pressure water with extreme precision.",
    "Gold Experience": "Gives life to objects and can heal injuries.",
    "Gold Experience Requiem": "Nullifies actions and resets events to zero.",
    "Goo Goo Dolls": "Shrinks the user and traps victims in confined spaces.",
    "Green Day": "Mold virus that spreads downward and rots living beings.",
    "Green Green Grass of Home": "Makes anything approaching shrink infinitely.",
    "Hanged Man": "Travels between reflective surfaces at light speed.",
    "Harvest": "A swarm Stand that gathers items and can drain nutrients.",
    "Heaven's Door": "Turns people into books and writes commands into them.",
    "Hey Ya!": "Grants motivational guidance and extreme luck.",
    "Hermit Purple": "Psychic vine Stand used for spirit photography and tracking.",
    "Hierophant Green": "Long-range emerald projectile attacks and body invasion.",
    "High Priestess": "Mineral-based Stand that shapeshifts and fuses with objects.",
    "Highway Star": "Tracks targets by scent and drains nutrients.",
    "Highway to Hell": "Shares all damage with a chosen victim.",
    "I Am a Rock": "Magnetically attracts objects based on value.",
    "In a Silent Way": "Turns sound effects into destructive physical forms.",
    "Jail House Lock": "Limits victims to remembering only three things at a time.",
    "Judgement": "Grants wishes by creating clay constructs.",
    "Jumpin' Jack Flash": "Removes gravity inside a zone.",
    "Justice": "Controls corpses using fog-like presence.",
    "Khnum": "Reshapes the user’s face.",
    "Killer Queen": "Turns anything it touches into a bomb.",
    "Killer Queen (Alternate)": "Similar bomb ability with explosive air bubbles.",
    "King Crimson": "Erases time and allows only the user to act within it.",
    "King Nothing": "Tracks scents and reconstructs broken objects.",
    "Kiss": "Places stickers that duplicate objects; removing them causes damage.",
    "Kraft Work": "Stops moving objects in midair.",
    "Limp Bizkit": "Reanimates the dead as invisible zombies.",
    "Little Feet": "Shrinks targets gradually.",
    "Love Deluxe": "Controls hair with extreme precision.",
    "Love Love Deluxe (Part 8)": "Enhanced hair manipulation.",
    "Lovers": "Microscopic Stand that attacks from inside the body.",
    "Made in Heaven": "Accelerates time for the entire universe.",
    "Magician's Red": "Controls powerful flames.",
    "Man in the Mirror": "Pulls victims into a mirror world.",
    "Manhattan Transfer": "Redirects bullets using air currents.",
    "Mandom": "Rewinds time by six seconds.",
    "Marilyn Manson": "Collects debt by force after losing bets.",
    "Matte Kudasai": "Transforms into requested objects.",
    "Metallica": "Manipulates iron within blood and surroundings.",
    "Milagro Man": "Forces victims into an endless cycle of spending money.",
    "Moody Blues": "Replays past events as realistic projections.",
    "Mr. President": "A key that contains a safe interior space.",
    "Notorious B.I.G": "An autonomous Stand that attacks the fastest target.",
    "November Rain": "Creates crushing raindrops with immense force.",
    "Nut King Call": "Attaches nuts and bolts to disassemble objects.",
    "Osiris": "Steals souls through gambling victories.",
    "Oasis": "Turns ground into a liquefied surface for swimming.",
    "Ozon Baby": "Creates extreme air pressure zones.",
    "Paisley Park": "A guidance Stand that manipulates information and technology.",
    "Paper Moon King": "Creates origami illusions that distort perception.",
    "Pearl Jam": "Heals people through specially prepared food.",
    "Planet Waves": "Pulls meteors from space.",
    "Purple Haze": "Releases a deadly flesh-melting virus.",
    "Ratt": "Fires darts that melt flesh.",
    "Red Hot Chili Pepper": "Electricity-based Stand that travels through power lines.",
    "Rolling Stones": "Predicts deaths and tries to ensure fate.",
    "Scary Monsters": "Transforms beings into dinosaurs.",
    "Schott Key No.1": "Generates heat through friction.",
    "Schott Key No.2": "Stores and releases heat energy.",
    "Sex Pistols": "Six bullet-riding entities that control trajectories.",
    "Sheer Heart Attack": "An indestructible heat-seeking bomb.",
    "Silver Chariot": "Extremely fast sword fighter Stand.",
    "Silver Chariot Requiem": "Manipulates souls and swaps bodies.",
    "Sky High": "Controls rod-like cryptid creatures.",
    "Soft & Wet": "Steals properties using soap bubbles.",
    "Soft & Wet: Go Beyond": "Fires invisible bubbles that transcend logic.",
    "Soft Machine": "Deflates victims and objects like balloons.",
    "Space Trucking": "Controls miniature model spaces with gravity effects.",
    "Speed King": "Stores heat and releases it explosively.",
    "Spice Girl": "Softens objects to make them rubber-like.",
    "Star Platinum": "Exceptional strength, speed, precision, and time stop.",
    "Star Platinum (Part 6)": "Same abilities with extended time stop.",
    "Sticky Fingers": "Creates zippers on anything.",
    "Stone Free": "Unravels body into string and enhances combat.",
    "Stray Cat": "Controls compressed air bubbles as projectiles.",
    "Strength": "Enhances and controls a large vehicle.",
    "Sugar Mountain": "Grants prosperity but punishes rule breakers.",
    "Sun": "Creates a miniature artificial sun.",
    "Super Fly": "A transmission tower that traps residents.",
    "Surface": "A wooden dummy that copies people’s movements.",
    "Survivor": "Emits waves that intensify anger and aggression.",
    "Talking Head": "Forces victims to lie.",
    "Tattoo You!": "Transfers body parts between people.",
    "The Fool": "Controls sand to form constructs.",
    "The Grateful Dead": "Rapidly ages living beings.",
    "The Hand": "Erases space with its right hand.",
    "The Hustle": "Manipulates muscles to steal objects.",
    "The Lock": "Feeds on guilt and grows heavier.",
    "The World": "Same type as Star Platinum with time stop.",
    "The World (Diego)": "Alternate version with time stop.",
    "Thoth": "A comic book that predicts the future.",
    "Tomb of the Boom": "Magnetic bomb triplets.",
    "Tower of Gray": "High-speed insect Stand that attacks tongues.",
    "Tusk Act 1": "Fires spinning nails.",
    "Tusk Act 2": "Nails create tracking wormholes.",
    "Tusk Act 3": "Enters dimensional holes created by Spin.",
    "Tusk Act 4": "Infinite Spin that bypasses all defenses.",
    "Tubular Bells": "Inflatable metal constructs formed from blood.",
    "Under World": "Replays past events from the ground.",
    "Vitamin C": "Softens living beings on contact.",
    "Walking Heart": "Extends high-heeled legs as blades.",
    "Weather Report": "Controls weather and atmospheric phenomena.",
    "Wheel of Fortune": "Weaponized car Stand with oil attacks.",
    "White Album": "Cryokinetic armor with absolute freezing.",
    "Whitesnake": "Extracts memories and Stands as discs.",
    "Wired": "Hook-based Stand that attacks from underground.",
    "Wonder of U": "Calamity manipulation that punishes pursuit.",
    "Yo-Yo Ma": "Automatic Stand that pretends to help while dissolving targets.",
    "Yellow Temperance": "Absorbing slime armor that devours matter."
    }

print("////// JOJO BIZARRE ADVENTURE RANDOM STAND SYSTEM //////")
time.sleep(3)
check = input("Please say 'Yes' if you are prepared to see if you have luck to get a good stand: ").strip().lower()
time.sleep(3)
advise = print("After you got your stand, an input will appear asking if you want to understand the stand abilitys, just say 'yes' or 'no'")
time.sleep(2)

if check == "yes":
    time.sleep(2)
    stand_arrow = random.choice(stands_jojo)
    print(f"\nYou have adquired a stand called {stand_arrow}")
    time.sleep(3)

    advise = input("Do you want to understand how this stand work?: ").strip().lower()
        
    if advise == "yes":
        print("\nStand ability")
        print(descriptions.get(stand_arrow, "ability not found."))
    else:
        print("Ok, maybe next time.")
else:
    print("Come back when you're ready")


        



